/**
 * 热力图看板 Mock 数据
 * 提供 18 个 APP 的模拟指标数据，用于前端预览和演示
 * 接入真实 API 后可删除此文件
 */
import type { HeatmapAppMetric, HeatmapDataResponse } from '../types/heatmap';

const mockApps: HeatmapAppMetric[] = [
  {
    appName: 'APP-短视频乐享版',
    deviceCount: 28500,
    subscriptionConversionRate: 0.35,
    subscriptionRetentionRate: 0.72,
    revenuePerDevice: 42.8,
    deviceType: 'phone',
    packageType: 'premium',
    yoyChange: { deviceCount: 0.12, subscriptionConversionRate: 0.05, subscriptionRetentionRate: -0.02, revenuePerDevice: 0.08 },
    momChange: { deviceCount: 0.03, subscriptionConversionRate: 0.01, subscriptionRetentionRate: -0.01, revenuePerDevice: 0.02 },
  },
  {
    appName: 'APP-影视尊享版',
    deviceCount: 15200,
    subscriptionConversionRate: 0.28,
    subscriptionRetentionRate: 0.65,
    revenuePerDevice: 35.5,
    deviceType: 'phone',
    packageType: 'advanced',
    yoyChange: { deviceCount: -0.05, subscriptionConversionRate: -0.03, subscriptionRetentionRate: 0.02, revenuePerDevice: -0.01 },
    momChange: { deviceCount: -0.02, subscriptionConversionRate: -0.01, subscriptionRetentionRate: 0.01, revenuePerDevice: 0.00 },
  },
  {
    appName: 'APP-智能家居管家',
    deviceCount: 4200,
    subscriptionConversionRate: 0.18,
    subscriptionRetentionRate: 0.48,
    revenuePerDevice: 18.3,
    deviceType: 'smart_hardware',
    packageType: 'basic',
    yoyChange: { deviceCount: -0.15, subscriptionConversionRate: -0.08, subscriptionRetentionRate: -0.05, revenuePerDevice: -0.12 },
    momChange: { deviceCount: -0.06, subscriptionConversionRate: -0.03, subscriptionRetentionRate: -0.02, revenuePerDevice: -0.04 },
  },
  {
    appName: 'APP-云存储极速版',
    deviceCount: 32000,
    subscriptionConversionRate: 0.42,
    subscriptionRetentionRate: 0.78,
    revenuePerDevice: 55.2,
    deviceType: 'phone',
    packageType: 'premium',
    yoyChange: { deviceCount: 0.18, subscriptionConversionRate: 0.07, subscriptionRetentionRate: 0.03, revenuePerDevice: 0.10 },
    momChange: { deviceCount: 0.05, subscriptionConversionRate: 0.02, subscriptionRetentionRate: 0.01, revenuePerDevice: 0.03 },
  },
  {
    appName: 'APP-安防监控Pro',
    deviceCount: 1800,
    subscriptionConversionRate: 0.08,
    subscriptionRetentionRate: 0.42,
    revenuePerDevice: 12.5,
    deviceType: 'smart_hardware',
    packageType: 'basic',
    yoyChange: { deviceCount: -0.25, subscriptionConversionRate: -0.10, subscriptionRetentionRate: -0.08, revenuePerDevice: -0.18 },
    momChange: { deviceCount: -0.10, subscriptionConversionRate: -0.05, subscriptionRetentionRate: -0.03, revenuePerDevice: -0.07 },
  },
  {
    appName: 'APP-儿童教育乐园',
    deviceCount: 8900,
    subscriptionConversionRate: 0.22,
    subscriptionRetentionRate: 0.55,
    revenuePerDevice: 25.0,
    deviceType: 'tablet',
    packageType: 'advanced',
    yoyChange: { deviceCount: 0.08, subscriptionConversionRate: 0.03, subscriptionRetentionRate: -0.01, revenuePerDevice: 0.04 },
    momChange: { deviceCount: 0.02, subscriptionConversionRate: 0.01, subscriptionRetentionRate: 0.00, revenuePerDevice: 0.01 },
  },
  {
    appName: 'APP-健康管理助手',
    deviceCount: 6500,
    subscriptionConversionRate: 0.15,
    subscriptionRetentionRate: 0.52,
    revenuePerDevice: 19.8,
    deviceType: 'phone',
    packageType: 'basic',
    yoyChange: { deviceCount: -0.03, subscriptionConversionRate: -0.02, subscriptionRetentionRate: 0.01, revenuePerDevice: -0.01 },
    momChange: { deviceCount: 0.01, subscriptionConversionRate: 0.00, subscriptionRetentionRate: 0.00, revenuePerDevice: 0.01 },
  },
  {
    appName: 'APP-直播互动版',
    deviceCount: 22000,
    subscriptionConversionRate: 0.38,
    subscriptionRetentionRate: 0.68,
    revenuePerDevice: 48.6,
    deviceType: 'phone',
    packageType: 'premium',
    yoyChange: { deviceCount: 0.22, subscriptionConversionRate: 0.09, subscriptionRetentionRate: 0.04, revenuePerDevice: 0.15 },
    momChange: { deviceCount: 0.08, subscriptionConversionRate: 0.03, subscriptionRetentionRate: 0.02, revenuePerDevice: 0.05 },
  },
  {
    appName: 'APP-音乐畅听版',
    deviceCount: 12500,
    subscriptionConversionRate: 0.25,
    subscriptionRetentionRate: 0.60,
    revenuePerDevice: 30.2,
    deviceType: 'phone',
    packageType: 'advanced',
    yoyChange: { deviceCount: 0.05, subscriptionConversionRate: 0.02, subscriptionRetentionRate: 0.01, revenuePerDevice: 0.03 },
    momChange: { deviceCount: 0.01, subscriptionConversionRate: 0.00, subscriptionRetentionRate: 0.00, revenuePerDevice: 0.01 },
  },
  {
    appName: 'APP-阅读精选版',
    deviceCount: 3800,
    subscriptionConversionRate: 0.12,
    subscriptionRetentionRate: 0.46,
    revenuePerDevice: 16.0,
    deviceType: 'tablet',
    packageType: 'basic',
    yoyChange: { deviceCount: -0.10, subscriptionConversionRate: -0.06, subscriptionRetentionRate: -0.04, revenuePerDevice: -0.08 },
    momChange: { deviceCount: -0.04, subscriptionConversionRate: -0.02, subscriptionRetentionRate: -0.01, revenuePerDevice: -0.03 },
  },
  {
    appName: 'APP-游戏竞技场',
    deviceCount: 45000,
    subscriptionConversionRate: 0.48,
    subscriptionRetentionRate: 0.82,
    revenuePerDevice: 68.5,
    deviceType: 'phone',
    packageType: 'premium',
    yoyChange: { deviceCount: 0.30, subscriptionConversionRate: 0.12, subscriptionRetentionRate: 0.06, revenuePerDevice: 0.20 },
    momChange: { deviceCount: 0.10, subscriptionConversionRate: 0.04, subscriptionRetentionRate: 0.02, revenuePerDevice: 0.07 },
  },
  {
    appName: 'APP-办公协同版',
    deviceCount: 9800,
    subscriptionConversionRate: 0.20,
    subscriptionRetentionRate: 0.58,
    revenuePerDevice: 22.0,
    deviceType: 'tablet',
    packageType: 'advanced',
    yoyChange: { deviceCount: 0.02, subscriptionConversionRate: 0.01, subscriptionRetentionRate: 0.00, revenuePerDevice: 0.01 },
    momChange: { deviceCount: 0.00, subscriptionConversionRate: 0.00, subscriptionRetentionRate: 0.00, revenuePerDevice: 0.00 },
  },
  {
    appName: 'APP-宠物看护版',
    deviceCount: null,
    subscriptionConversionRate: 0.10,
    subscriptionRetentionRate: null,
    revenuePerDevice: 14.0,
    deviceType: 'smart_hardware',
    packageType: 'basic',
    yoyChange: { deviceCount: null, subscriptionConversionRate: -0.04, subscriptionRetentionRate: null, revenuePerDevice: -0.06 },
    momChange: { deviceCount: null, subscriptionConversionRate: -0.02, subscriptionRetentionRate: null, revenuePerDevice: -0.02 },
  },
  {
    appName: 'APP-出行导航版',
    deviceCount: 18000,
    subscriptionConversionRate: 0.30,
    subscriptionRetentionRate: 0.62,
    revenuePerDevice: 38.0,
    deviceType: 'phone',
    packageType: 'advanced',
    yoyChange: { deviceCount: 0.06, subscriptionConversionRate: 0.02, subscriptionRetentionRate: 0.01, revenuePerDevice: 0.04 },
    momChange: { deviceCount: 0.02, subscriptionConversionRate: 0.01, subscriptionRetentionRate: 0.00, revenuePerDevice: 0.01 },
  },
  {
    appName: 'APP-购物优选版',
    deviceCount: 0,
    subscriptionConversionRate: 0,
    subscriptionRetentionRate: 0,
    revenuePerDevice: 0,
    deviceType: 'phone',
    packageType: 'basic',
    yoyChange: { deviceCount: -0.30, subscriptionConversionRate: -0.15, subscriptionRetentionRate: -0.20, revenuePerDevice: -0.25 },
    momChange: { deviceCount: -0.18, subscriptionConversionRate: -0.10, subscriptionRetentionRate: -0.12, revenuePerDevice: -0.16 },
  },
  {
    appName: 'APP-运动健身版',
    deviceCount: 7200,
    subscriptionConversionRate: null,
    subscriptionRetentionRate: 0.50,
    revenuePerDevice: null,
    deviceType: 'phone',
    packageType: 'advanced',
    yoyChange: { deviceCount: 0.04, subscriptionConversionRate: null, subscriptionRetentionRate: 0.01, revenuePerDevice: null },
    momChange: { deviceCount: 0.01, subscriptionConversionRate: null, subscriptionRetentionRate: 0.00, revenuePerDevice: null },
  },
  {
    appName: 'APP-新闻资讯版',
    deviceCount: 25000,
    subscriptionConversionRate: 0.32,
    subscriptionRetentionRate: 0.70,
    revenuePerDevice: 40.0,
    deviceType: 'phone',
    packageType: 'premium',
    yoyChange: { deviceCount: 0.10, subscriptionConversionRate: 0.04, subscriptionRetentionRate: 0.02, revenuePerDevice: 0.06 },
    momChange: { deviceCount: 0.03, subscriptionConversionRate: 0.01, subscriptionRetentionRate: 0.01, revenuePerDevice: 0.02 },
  },
  {
    appName: 'APP-社交通讯版',
    deviceCount: 38000,
    subscriptionConversionRate: 0.45,
    subscriptionRetentionRate: 0.75,
    revenuePerDevice: 52.0,
    deviceType: 'phone',
    packageType: 'premium',
    yoyChange: { deviceCount: 0.15, subscriptionConversionRate: 0.06, subscriptionRetentionRate: 0.03, revenuePerDevice: 0.09 },
    momChange: { deviceCount: 0.04, subscriptionConversionRate: 0.02, subscriptionRetentionRate: 0.01, revenuePerDevice: 0.03 },
  },
];

export const mockHeatmapData: HeatmapDataResponse = {
  apps: mockApps,
  updatedAt: new Date().toISOString(),
};
